name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api-pgd
    - name: Create pgadmin_data volume
      run: sudo mkdir -p pgadmin_data && sudo chown -R 5050:5050 ./pgadmin_data/
    - name: Run docker-compose
      run: docker-compose up -d
    - name: run tests
      run: docker exec -it api-pgd_web_1 /usr/local/bin/pytest /home/api-pgd/ test_api.py -k-test_patch_user_self_change_cod_unidade
